language: node_js
node_js:
  - "5.9.0"
before_script:
  - npm install -g bower
  - bower install
after_success:
  - ./node_modules/.bin/gulp coveralls
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
services:
  - mysql
  - redis
env:
  - TRAVIS=travis CXX=g++-4.8